[package]
name = "iracing-overlays"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skulpin = { version = "0.14.1", default-features = false, features = ["winit-app", "winit-25"] }
log = "0.4"
env_logger = "0.6"
tokio = { version = "1.15.0", features = [ "sync" ] }

[patch.crates-io]
rafx-api = { path = "/Volumes/git/rafx/rafx-api" }
skulpin-renderer = { path = "/Volumes/git/skulpin/skulpin-renderer" }
