name: MSBuild
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clippy
        uses: rustup component add clippy
      - name: Run lints
        uses: cargo clippy -- -D warnings

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  release:
    needs: build
    runs-on: windows-latest
    if: ${{GITHUB_REF_TYPE == 'tag'}}
    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build (release)
        run: cargo build --release
      
      - uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/uberlays.exe
